#!/bin/bash

# rust - Redundant Uplink SwiTchero
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2012 (C) Thomas Liske <thomas@fiasko-nw.net>
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

if [ "$IFACE" = lo ]; then
	exit 0
fi

if [ "$ADDRFAM" != inet ] || [ "$METHOD" != static ] ; then
	exit 0
fi

RUST_IPADDR="$IF_ADDRESS"
RUST_PFLEN="$IF_NETMASK"
RUST_GATEWAY="$IF_RUST_GATEWAY"
RUST_GATEWAY="${RUST_GATEWAY:-$IF_POINTOPOINT}"
RUST_GATEWAY="${RUST_GATEWAY:-$IF_GATEWAY}"
RUST_IFACE="$IFACE"
RUST_MATCH="$IF_RUST_USEMATCH"

. /etc/rust/rust.lib

if [ -z "$RUST_GATEWAY" ] ; then
    rust_log "link has no gateway"
    exit 0
fi

case "$MODE" in
    start)
	rust_add_uplink
	;;

    stop)
	rust_del_uplink
	;;

    *)
	rust_log "unknown mode: \"$MODE\""
	exit 1
	;;
esac
